version: "3.6"
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "zero", "-h", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
  graphql-engine:
    image: hasura/graphql-engine:v2.29.0
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./hasura/migrations:/migrations
      - ./hasura/metadata:/metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_ADMIN_SECRET: 111
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  db_data:
